name: firebase_user_avatar
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  firebase_core: ^0.5.2
  firebase_auth: ^0.18.3
  firebase_storage: ^5.0.1
  cloud_firestore: ^0.14.3
  image_picker: ^0.6.7+14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
